name: Create Issue Pranch

on:
    issues:
        types: [assigned]
    # issue_comment:
    #    types: [created]
    # pull_request:
    #    types: [closed]

jobs:
  Create-issue-branch-job:
    runs-on: windows-latest
    steps:
    - name: Create Issue Branch
      uses: robvanderleek/create-issue-branch@v1.5
      
